services:
    mariadb:
        image: mariadb:10.5.9
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: alpine
        ports:
            - "3306:3306"
        volumes:
            - type: volume
                source: maria-data
                target: /var/lib/mysql
    redis:
        image: redis:5.0.9
        restart: always
        ports:
            - "6379:6379"
volumes:
    maria-data: