version: "3.9"
services:
  mariadb:
    image: mariadb:10.5.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gacha
      MYSQL_DATABASE: gacha
      MYSQL_USER: gacha
      MYSQL_PASSWORD: gacha
  redis:
    image: redis:5.0.9
    restart: always
  gacha:
    image: gacha
    restart: always
    environment:
      GACHA_MYSQL_CONNECTION_STRING: gacha:gacha@tcp(mariadb:3306)/
      GACHA_REDIS_LOCATION: redis:6379
      GACHA_RMQ_CONNECTION_STRING: amqp://gacha:gacha@${DOCKER_GATEWAY_HOST:-host.docker.internal}:5672/
      GACHA_RMQ_CHANNEL: gacha_v0
    depends_on:
      - mariadb
      - redis
    volumes:
      - type: volume
        source: gacha-log
        target: /app/log
volumes:
  gacha-log: