version: "3.9"
services:
  mariadb:
    image: mariadb:10.5.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gacha
      MYSQL_DATABASE: gacha
      MYSQL_USER: gacha
      MYSQL_PASSWORD: gacha
    expose:
      - "3306"
  redis:
    image: redis:5.0.9
    restart: always
    expose:
      - "6379"
  gacha:
    image: gacha
    restart: always
    environment:
      MYSQL_CONNECTION_STRING: gacha:gacha@tcp(server:3306)/
      REDIS_LOCATION: server:6379
    depends_on:
      - mariadb
      - redis
    volumes:
      - type: volume
        source: gacha-log
        target: /app/log
volumes:
  gacha-log: