// Code generated by entc, DO NOT EDIT.

package drop

const (
	// Label holds the string label denoting the drop type in the database.
	Label = "drop"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRate holds the string denoting the rate field in the database.
	FieldRate = "rate"
	// FieldSeries holds the string denoting the series field in the database.
	FieldSeries = "series"
	// Table holds the table name of the drop in the database.
	Table = "drops"
)

// Columns holds all SQL columns for drop fields.
var Columns = []string{
	FieldID,
	FieldRate,
	FieldSeries,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
