// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/karashiiro/gacha/ent/drop"
)

// Drop is the model entity for the Drop schema.
type Drop struct {
	config `json:"-"`
	// ID of the ent.
	ID uint32 `json:"id,omitempty"`
	// Rate holds the value of the "rate" field.
	Rate float32 `json:"rate,omitempty"`
	// Series holds the value of the "series" field.
	Series string `json:"series,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Drop) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case drop.FieldRate:
			values[i] = &sql.NullFloat64{}
		case drop.FieldID:
			values[i] = &sql.NullInt64{}
		case drop.FieldSeries:
			values[i] = &sql.NullString{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type Drop", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Drop fields.
func (d *Drop) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case drop.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			d.ID = uint32(value.Int64)
		case drop.FieldRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value.Valid {
				d.Rate = float32(value.Float64)
			}
		case drop.FieldSeries:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field series", values[i])
			} else if value.Valid {
				d.Series = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Drop.
// Note that you need to call Drop.Unwrap() before calling this method if this Drop
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Drop) Update() *DropUpdateOne {
	return (&DropClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the Drop entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Drop) Unwrap() *Drop {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Drop is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Drop) String() string {
	var builder strings.Builder
	builder.WriteString("Drop(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", rate=")
	builder.WriteString(fmt.Sprintf("%v", d.Rate))
	builder.WriteString(", series=")
	builder.WriteString(d.Series)
	builder.WriteByte(')')
	return builder.String()
}

// Drops is a parsable slice of Drop.
type Drops []*Drop

func (d Drops) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
