// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/karashiiro/gacha/ent/drop"
	"github.com/karashiiro/gacha/ent/series"
)

// Drop is the model entity for the Drop schema.
type Drop struct {
	config `json:"-"`
	// ID of the ent.
	ID uint32 `json:"id,omitempty"`
	// ObjectID holds the value of the "object_id" field.
	ObjectID uint32 `json:"object_id,omitempty"`
	// Rate holds the value of the "rate" field.
	Rate float32 `json:"rate,omitempty"`
	// SeriesID holds the value of the "series_id" field.
	SeriesID uint32 `json:"series_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DropQuery when eager-loading is set.
	Edges DropEdges `json:"edges"`
}

// DropEdges holds the relations/edges for other nodes in the graph.
type DropEdges struct {
	// Series holds the value of the series edge.
	Series *Series `json:"series,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SeriesOrErr returns the Series value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DropEdges) SeriesOrErr() (*Series, error) {
	if e.loadedTypes[0] {
		if e.Series == nil {
			// The edge series was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: series.Label}
		}
		return e.Series, nil
	}
	return nil, &NotLoadedError{edge: "series"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Drop) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case drop.FieldRate:
			values[i] = &sql.NullFloat64{}
		case drop.FieldID, drop.FieldObjectID, drop.FieldSeriesID:
			values[i] = &sql.NullInt64{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type Drop", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Drop fields.
func (d *Drop) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case drop.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			d.ID = uint32(value.Int64)
		case drop.FieldObjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field object_id", values[i])
			} else if value.Valid {
				d.ObjectID = uint32(value.Int64)
			}
		case drop.FieldRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value.Valid {
				d.Rate = float32(value.Float64)
			}
		case drop.FieldSeriesID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field series_id", values[i])
			} else if value.Valid {
				d.SeriesID = uint32(value.Int64)
			}
		}
	}
	return nil
}

// QuerySeries queries the "series" edge of the Drop entity.
func (d *Drop) QuerySeries() *SeriesQuery {
	return (&DropClient{config: d.config}).QuerySeries(d)
}

// Update returns a builder for updating this Drop.
// Note that you need to call Drop.Unwrap() before calling this method if this Drop
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Drop) Update() *DropUpdateOne {
	return (&DropClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the Drop entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Drop) Unwrap() *Drop {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Drop is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Drop) String() string {
	var builder strings.Builder
	builder.WriteString("Drop(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", object_id=")
	builder.WriteString(fmt.Sprintf("%v", d.ObjectID))
	builder.WriteString(", rate=")
	builder.WriteString(fmt.Sprintf("%v", d.Rate))
	builder.WriteString(", series_id=")
	builder.WriteString(fmt.Sprintf("%v", d.SeriesID))
	builder.WriteByte(')')
	return builder.String()
}

// Drops is a parsable slice of Drop.
type Drops []*Drop

func (d Drops) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
